# Getting Financial Data - Google Finance

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [6]:
import pandas as pd
import pandas_datareader
import datetime as dt

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is)

In [2]:
startdate = dt.datetime(2015, 1, 1)

enddate = dt.datetime.today()

startdate

datetime.datetime(2015, 1, 1, 0, 0)

### Step 3. Select the Apple, Tesla, Twitter, IBM, LinkedIn stocks symbols and assign them to a variable called stocks

In [3]:
stocks = ['AAPL', 'TSLA', 'IBM', 'LNKD']

### Step 4. Read the data from google, assign to df and print it

In [ ]:
df = pandas_datareader.DataReader(stocks, 'yahoo', startdate, enddate)

In [13]:
df

Attributes        High                                      Low              \
Symbols           AAPL         IBM LNKD        TSLA        AAPL         IBM
Date
2015-01-02  111.440002  163.309998  NaN  223.250000  107.349998  161.000000
2015-01-05  108.650002  161.270004  NaN  216.500000  105.410004  159.190002
2015-01-06  107.430000  159.960007  NaN  214.199997  104.629997  155.169998
2015-01-07  108.199997  157.199997  NaN  214.779999  106.699997  154.029999
2015-01-08  112.150002  159.039993  NaN  213.800003  108.699997  155.550003
2015-01-09  113.250000  160.339996  NaN  209.979996  110.209999  157.250000
2015-01-12  112.629997  159.250000  NaN  204.470001  108.800003  155.759995
2015-01-13  112.800003  159.970001  NaN  207.610001  108.910004  155.679993
2015-01-14  110.489998  156.490005  NaN  195.199997  108.500000  153.740005
2015-01-15  110.059998  156.970001  NaN  195.750000  106.660004  154.160004
2015-01-16  107.580002  157.630005  NaN  194.490005  105.199997  153.820007
2015-01-20  108.970001  157.330002  NaN  194.119995  106.500000  154.029999
2015-01-21  111.059998  154.500000  NaN  198.679993  108.269997  151.070007
2015-01-22  112.470001  155.720001  NaN  203.240005  109.720001  151.759995
2015-01-23  113.750000  157.600006  NaN  203.500000  111.529999  154.889999
2015-01-26  114.360001  159.460007  NaN  208.619995  112.800003  155.770004
2015-01-27  112.480003  155.089996  NaN  208.029999  109.029999  152.589996
2015-01-28  118.120003  154.529999  NaN  206.369995  115.309998  151.550003
2015-01-29  119.190002  155.580002  NaN  205.979996  115.559998  149.520004
2015-01-30  120.000000  155.240005  NaN  207.470001  116.849998  153.039993
2015-02-02  119.169998  154.660004  NaN  211.949997  116.080002  151.509995
2015-02-03  119.089996  158.600006  NaN  220.369995  117.610001  154.750000
2015-02-04  120.510002  158.710007  NaN  221.479996  118.309998  156.699997
2015-02-05  120.230003  158.589996  NaN  225.479996  119.250000  157.149994
2015-02-06  120.250000  158.080002  NaN  223.399994  118.449997  156.229996
2015-02-09  119.839996  157.500000  NaN  217.929993  118.430000  155.399994
2015-02-10  122.150002  158.559998  NaN  220.500000  120.160004  155.080002
2015-02-11  124.919998  159.089996  NaN  214.740005  122.500000  157.169998
2015-02-12  127.480003  159.500000  NaN  203.089996  125.570000  158.089996
2015-02-13  127.279999  160.800003  NaN  205.990005  125.650002  158.639999
...                ...         ...  ...         ...         ...         ...
2019-02-22  173.000000  139.380005  NaN  296.500000  171.380005  138.429993
2019-02-25  175.869995  140.470001  NaN  302.899994  173.949997  139.320007
2019-02-26  175.300003  140.490005  NaN  302.010010  173.169998  139.470001
2019-02-27  175.000000  139.570007  NaN  316.299988  172.729996  138.399994
2019-02-28  174.910004  139.059998  NaN  320.000000  172.919998  137.720001
2019-03-01  175.149994  140.039993  NaN  307.130005  172.889999  138.639999
2019-03-04  177.750000  140.080002  NaN  299.000000  173.970001  137.169998
2019-03-05  176.000000  138.740005  NaN  284.000000  174.539993  137.559998
2019-03-06  175.490005  138.389999  NaN  281.510010  173.940002  136.720001
2019-03-07  174.440002  136.889999  NaN  284.700012  172.020004  134.630005
2019-03-08  173.070007  135.240005  NaN  285.589996  169.500000  133.580002
2019-03-11  179.119995  137.729996  NaN  291.279999  175.350006  135.839996
2019-03-12  182.669998  139.699997  NaN  288.070007  179.369995  137.860001
2019-03-13  183.300003  139.320007  NaN  291.989990  180.919998  137.850006
2019-03-14  184.100006  138.940002  NaN  295.390015  182.559998  138.059998
2019-03-15  187.330002  140.330002  NaN  283.720001  183.740005  139.229996
2019-03-18  188.389999  140.369995  NaN  278.049988  185.789993  138.720001
2019-03-19  188.990005  141.699997  NaN  273.299988  185.919998  140.000000
2019-03-20  189.490005  140.699997  NaN  274.970001  184.729996  138.979996
2019-03-21  196.330002  142.119995  NaN  276.450012  189.809998  138.880005
2019-03-22  197.690002  141.440002  NaN  272.799988  190.779999  138.899994
2019-03-25  191.979996  139.910004  NaN  263.179993  186.600006  138.350006
2019-03-26  192.880005  141.020004  NaN  270.260010  184.580002  139.419998
2019-03-27  189.759995  140.490005  NaN  275.369995  186.550003  138.399994
2019-03-28  189.559998  140.440002  NaN  280.329987  187.529999  139.100006
2019-03-29  190.080002  141.220001  NaN  280.160004  188.539993  140.149994
2019-04-01  191.679993  143.410004  NaN  289.200012  188.380005  141.509995
2019-04-02  194.460007  143.949997  NaN  289.440002  191.050003  142.600006
2019-04-03  196.500000  144.220001  NaN  296.170013  193.149994  143.009995
2019-04-04  196.360001  144.139999  NaN  271.200012  194.710007  142.539993

Attributes                         Open                 ...     Close  \
Symbols    LNKD        TSLA        AAPL         IBM     ...      LNKD
Date                                                    ...
2015-01-02  NaN  213.259995  111.389999  161.309998     ...       NaN
2015-01-05  NaN  207.160004  108.290001  161.270004     ...       NaN
2015-01-06  NaN  204.210007  106.540001  159.669998     ...       NaN
2015-01-07  NaN  209.779999  107.199997  157.199997     ...       NaN
2015-01-08  NaN  210.009995  109.230003  156.240005     ...       NaN
2015-01-09  NaN  204.960007  112.669998  158.419998     ...       NaN
2015-01-12  NaN  199.250000  112.599998  159.000000     ...       NaN
2015-01-13  NaN  200.910004  111.430000  157.259995     ...       NaN
2015-01-14  NaN  185.000000  109.040001  154.860001     ...       NaN
2015-01-15  NaN  190.000000  110.000000  156.690002     ...       NaN
2015-01-16  NaN  189.649994  107.029999  153.820007     ...       NaN
2015-01-20  NaN  187.039993  107.839996  156.699997     ...       NaN
2015-01-21  NaN  189.509995  108.949997  153.029999     ...       NaN
2015-01-22  NaN  195.199997  110.260002  151.940002     ...       NaN
2015-01-23  NaN  198.330002  112.300003  155.029999     ...       NaN
2015-01-26  NaN  201.050003  113.739998  158.259995     ...       NaN
2015-01-27  NaN  203.300003  112.419998  154.940002     ...       NaN
2015-01-28  NaN  198.419998  117.629997  154.000000     ...       NaN
2015-01-29  NaN  196.500000  116.320000  151.380005     ...       NaN
2015-01-30  NaN  203.000000  118.400002  153.910004     ...       NaN
2015-02-02  NaN  203.300003  118.050003  154.000000     ...       NaN
2015-02-03  NaN  211.270004  118.500000  154.750000     ...       NaN
2015-02-04  NaN  216.800003  118.500000  157.210007     ...       NaN
2015-02-05  NaN  219.639999  120.019997  157.289993     ...       NaN
2015-02-06  NaN  216.500000  120.019997  157.339996     ...       NaN
2015-02-09  NaN  211.990005  118.550003  156.000000     ...       NaN
2015-02-10  NaN  215.000000  120.169998  156.740005     ...       NaN
2015-02-11  NaN  207.279999  122.769997  157.759995     ...       NaN
2015-02-12  NaN  193.279999  126.059998  158.720001     ...       NaN
2015-02-13  NaN  200.910004  127.279999  158.779999     ...       NaN
...         ...         ...         ...         ...     ...       ...
2019-02-22  NaN  292.100006  171.580002  138.729996     ...       NaN
2019-02-25  NaN  297.000000  174.160004  140.000000     ...       NaN
2019-02-26  NaN  288.769989  173.710007  139.669998     ...       NaN
2019-02-27  NaN  300.549988  173.210007  139.250000     ...       NaN
2019-02-28  NaN  310.809998  174.320007  138.770004     ...       NaN
2019-03-01  NaN  291.899994  174.279999  139.309998     ...       NaN
2019-03-04  NaN  282.779999  175.690002  139.990005     ...       NaN
2019-03-05  NaN  270.100006  175.940002  138.369995     ...       NaN
2019-03-06  NaN  274.390015  174.669998  138.119995     ...       NaN
2019-03-07  NaN  274.250000  173.869995  136.610001     ...       NaN
2019-03-08  NaN  275.890015  170.320007  134.210007     ...       NaN
2019-03-11  NaN  280.500000  175.490005  136.029999     ...       NaN
2019-03-12  NaN  281.059998  180.000000  138.520004     ...       NaN
2019-03-13  NaN  282.700012  182.250000  138.050003     ...       NaN
2019-03-14  NaN  288.290009  183.899994  138.509995     ...       NaN
2019-03-15  NaN  274.399994  184.850006  139.369995     ...       NaN
2019-03-18  NaN  267.299988  185.800003  139.830002     ...       NaN
2019-03-19  NaN  263.459991  188.350006  140.960007     ...       NaN
2019-03-20  NaN  266.299988  186.229996  140.529999     ...       NaN
2019-03-21  NaN  268.450012  190.020004  139.100006     ...       NaN
2019-03-22  NaN  264.000000  195.339996  140.970001     ...       NaN
2019-03-25  NaN  254.460007  191.509995  139.059998     ...       NaN
2019-03-26  NaN  264.429993  191.660004  139.929993     ...       NaN
2019-03-27  NaN  268.179993  188.750000  140.410004     ...       NaN
2019-03-28  NaN  275.100006  188.949997  139.910004     ...       NaN
2019-03-29  NaN  274.500000  189.830002  140.500000     ...       NaN
2019-04-01  NaN  281.279999  191.639999  141.509995     ...       NaN
2019-04-02  NaN  283.880005  191.089996  143.350006     ...       NaN
2019-04-03  NaN  287.170013  193.250000  143.649994     ...       NaN
2019-04-04  NaN  260.589996  194.789993  143.619995     ...       NaN

Attributes                   Volume                                Adj Close  \
Symbols           TSLA         AAPL         IBM LNKD        TSLA        AAPL
Date
2015-01-02  219.309998   53204600.0   5525500.0  NaN   4764400.0  101.528191
2015-01-05  210.089996   64285500.0   4880400.0  NaN   5368500.0   98.667984
2015-01-06  211.279999   65797100.0   6146700.0  NaN   6261900.0   98.677261
2015-01-07  210.949997   40105900.0   4701800.0  NaN   2968400.0  100.060936
2015-01-08  210.619995   59364500.0   4236800.0  NaN   3442500.0  103.905510
2015-01-09  206.660004   53699500.0   4484800.0  NaN   4591300.0  104.016945
2015-01-12  202.210007   49650800.0   4182800.0  NaN   5944200.0  101.453903
2015-01-13  204.250000   67091900.0   4377500.0  NaN   4477300.0  102.354675
2015-01-14  192.690002   48337000.0   4690300.0  NaN  11551900.0  101.964645
2015-01-15  191.869995   60014000.0   4248400.0  NaN   5216500.0   99.197289
2015-01-16  193.070007   78513300.0   5756000.0  NaN   3603200.0   98.426529
2015-01-20  191.929993   49899900.0   8017800.0  NaN   4489400.0  100.961716
2015-01-21  196.570007   48575900.0  11897100.0  NaN   4153000.0  101.732506
2015-01-22  201.619995   53796400.0   6120100.0  NaN   4116900.0  104.379112
2015-01-23  201.289993   46464800.0   4812200.0  NaN   3438600.0  104.917725
2015-01-26  206.550003   55615000.0   7888100.0  NaN   3234500.0  105.029175
2015-01-27  205.979996   95568700.0   5659600.0  NaN   2781000.0  101.351738
2015-01-28  199.369995  146477100.0   4495900.0  NaN   3149600.0  107.081474
2015-01-29  205.199997   84436400.0   8320800.0  NaN   3548100.0  110.415276
2015-01-30  203.600006   83745500.0   6563600.0  NaN   3007000.0  108.799446
2015-02-02  210.940002   62739100.0   4712200.0  NaN   4149200.0  110.164543
2015-02-03  218.360001   51915700.0   5536300.0  NaN   4812900.0  110.183121
2015-02-04  218.550003   70149700.0   3678500.0  NaN   3305400.0  111.028168
2015-02-05  220.990005   42246200.0   5253600.0  NaN   3522900.0  111.820625
2015-02-06  217.360001   43706600.0   3225000.0  NaN   3233200.0  110.879021
2015-02-09  217.479996   38889800.0   3057700.0  NaN   3472400.0  111.615524
2015-02-10  216.289993   62008500.0   4440600.0  NaN   5390500.0  113.759834
2015-02-11  212.800003   73561800.0   3626700.0  NaN   9769100.0  116.426216
2015-02-12  202.880005   74474500.0   3333100.0  NaN  15649600.0  117.899254
2015-02-13  203.770004   54272200.0   3706900.0  NaN   6191000.0  118.477295
...                ...          ...         ...  ...         ...         ...
2019-02-22  294.709991   18913200.0   3113700.0  NaN   5740600.0  172.970001
2019-02-25  298.769989   21873400.0   3194200.0  NaN   6626500.0  174.229996
2019-02-26  297.859985   17070200.0   3060400.0  NaN   8582500.0  174.330002
2019-02-27  314.739990   27835400.0   2530900.0  NaN  11183900.0  174.869995
2019-02-28  319.880005   28215400.0   3457800.0  NaN  10520700.0  173.149994
2019-03-01  294.790009   25886200.0   3030000.0  NaN  22911400.0  174.970001
2019-03-04  285.359985   27436200.0   3406900.0  NaN  17096800.0  175.850006
2019-03-05  276.540009   19737400.0   4250300.0  NaN  18764700.0  175.529999
2019-03-06  276.239990   20810400.0   2768300.0  NaN  10335500.0  174.520004
2019-03-07  276.589996   24796400.0   4358800.0  NaN   9442500.0  172.500000
2019-03-08  284.140015   23999400.0   3773600.0  NaN   8819600.0  172.910004
2019-03-11  290.920013   32011000.0   3939300.0  NaN   7392300.0  178.899994
2019-03-12  283.359985   32467600.0   3954700.0  NaN   7504100.0  180.910004
2019-03-13  288.959991   31032500.0   3173200.0  NaN   6844700.0  181.710007
2019-03-14  289.959991   23579500.0   2738600.0  NaN   7103400.0  183.729996
2019-03-15  275.429993   39042900.0   7153700.0  NaN  14785500.0  186.119995
2019-03-18  269.489990   26219800.0   3268500.0  NaN  10281000.0  188.020004
2019-03-19  267.470001   31646400.0   3482300.0  NaN  11800600.0  186.529999
2019-03-20  273.600006   31035200.0   3649500.0  NaN   6908200.0  188.160004
2019-03-21  274.019989   51034200.0   3605400.0  NaN   5947100.0  195.089996
2019-03-22  264.529999   42407700.0   3877200.0  NaN   8745600.0  191.050003
2019-03-25  260.420013   43845300.0   2839800.0  NaN  10215000.0  188.740005
2019-03-26  267.769989   49800500.0   2553700.0  NaN   7350900.0  186.789993
2019-03-27  274.829987   29848400.0   3098200.0  NaN   8779200.0  188.470001
2019-03-28  278.619995   20780400.0   2663900.0  NaN   6774100.0  188.720001
2019-03-29  279.859985   23564000.0   3101400.0  NaN   5991300.0  189.949997
2019-04-01  289.179993   27862000.0   3984300.0  NaN   8110400.0  191.240005
2019-04-02  285.880005   22765700.0   2404800.0  NaN   5478900.0  194.020004
2019-04-03  291.809998   23249700.0   2681200.0  NaN   7919400.0  195.350006
2019-04-04  267.779999   18747318.0   2706066.0  NaN  23534862.0  195.690002

Attributes
Symbols            IBM LNKD        TSLA
Date
2015-01-02  135.278397  NaN  219.309998
2015-01-05  133.149841  NaN  210.089996
2015-01-06  130.278320  NaN  211.279999
2015-01-07  129.426880  NaN  210.949997
2015-01-08  132.239990  NaN  210.619995
2015-01-09  132.815948  NaN  206.660004
2015-01-12  130.587219  NaN  202.210007
2015-01-13  130.896027  NaN  204.250000
2015-01-14  130.052948  NaN  192.690002
2015-01-15  129.026199  NaN  191.869995
2015-01-16  131.171494  NaN  193.070007
2015-01-20  131.012863  NaN  191.929993
2015-01-21  126.956032  NaN  196.570007
2015-01-22  129.710678  NaN  201.619995
2015-01-23  130.111374  NaN  201.289993
2015-01-26  130.520401  NaN  206.550003
2015-01-27  128.274918  NaN  205.979996
2015-01-28  126.505280  NaN  199.369995
2015-01-29  129.785812  NaN  205.199997
2015-01-30  127.974457  NaN  203.600006
2015-02-02  129.101334  NaN  210.940002
2015-02-03  132.281693  NaN  218.360001
2015-02-04  131.021240  NaN  218.550003
2015-02-05  131.814255  NaN  220.990005
2015-02-06  131.738586  NaN  217.360001
2015-02-09  130.923187  NaN  217.479996
2015-02-10  133.285309  NaN  216.289993
2015-02-11  132.982666  NaN  212.800003
2015-02-12  133.251663  NaN  202.880005
2015-02-13  134.831985  NaN  203.770004
...                ...  ...         ...
2019-02-22  139.250000  NaN  294.709991
2019-02-25  139.460007  NaN  298.769989
2019-02-26  139.720001  NaN  297.859985
2019-02-27  139.169998  NaN  314.739990
2019-02-28  138.130005  NaN  319.880005
2019-03-01  139.199997  NaN  294.790009
2019-03-04  138.429993  NaN  285.359985
2019-03-05  137.880005  NaN  276.540009
2019-03-06  136.979996  NaN  276.239990
2019-03-07  135.360001  NaN  276.589996
2019-03-08  135.089996  NaN  284.140015
2019-03-11  137.710007  NaN  290.920013
2019-03-12  138.279999  NaN  283.359985
2019-03-13  138.559998  NaN  288.959991
2019-03-14  138.789993  NaN  289.959991
2019-03-15  139.429993  NaN  275.429993
2019-03-18  140.210007  NaN  269.489990
2019-03-19  140.490005  NaN  267.470001
2019-03-20  139.600006  NaN  273.600006
2019-03-21  141.440002  NaN  274.019989
2019-03-22  139.449997  NaN  264.529999
2019-03-25  139.179993  NaN  260.420013
2019-03-26  140.220001  NaN  267.769989
2019-03-27  139.240005  NaN  274.829987
2019-03-28  139.919998  NaN  278.619995
2019-03-29  141.100006  NaN  279.859985
2019-04-01  143.300003  NaN  289.179993
2019-04-02  143.000000  NaN  285.880005
2019-04-03  143.630005  NaN  291.809998
2019-04-04  142.779999  NaN  267.779999

[1071 rows x 24 columns]

### Step 5.  What is the type of structure of df ?

### Step 6. Print all the Items axis values
#### To learn more about the Panel structure go to [documentation](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel)

In [14]:
df.items

<bound method DataFrame.iteritems of Attributes        High                                      Low              \
Symbols           AAPL         IBM LNKD        TSLA        AAPL         IBM
Date
2015-01-02  111.440002  163.309998  NaN  223.250000  107.349998  161.000000
2015-01-05  108.650002  161.270004  NaN  216.500000  105.410004  159.190002
2015-01-06  107.430000  159.960007  NaN  214.199997  104.629997  155.169998
2015-01-07  108.199997  157.199997  NaN  214.779999  106.699997  154.029999
2015-01-08  112.150002  159.039993  NaN  213.800003  108.699997  155.550003
2015-01-09  113.250000  160.339996  NaN  209.979996  110.209999  157.250000
2015-01-12  112.629997  159.250000  NaN  204.470001  108.800003  155.759995
2015-01-13  112.800003  159.970001  NaN  207.610001  108.910004  155.679993
2015-01-14  110.489998  156.490005  NaN  195.199997  108.500000  153.740005
2015-01-15  110.059998  156.970001  NaN  195.750000  106.660004  154.160004
2015-01-16  107.580002  157.630005  NaN  194.490005  105.199997  153.820007
2015-01-20  108.970001  157.330002  NaN  194.119995  106.500000  154.029999
2015-01-21  111.059998  154.500000  NaN  198.679993  108.269997  151.070007
2015-01-22  112.470001  155.720001  NaN  203.240005  109.720001  151.759995
2015-01-23  113.750000  157.600006  NaN  203.500000  111.529999  154.889999
2015-01-26  114.360001  159.460007  NaN  208.619995  112.800003  155.770004
2015-01-27  112.480003  155.089996  NaN  208.029999  109.029999  152.589996
2015-01-28  118.120003  154.529999  NaN  206.369995  115.309998  151.550003
2015-01-29  119.190002  155.580002  NaN  205.979996  115.559998  149.520004
2015-01-30  120.000000  155.240005  NaN  207.470001  116.849998  153.039993
2015-02-02  119.169998  154.660004  NaN  211.949997  116.080002  151.509995
2015-02-03  119.089996  158.600006  NaN  220.369995  117.610001  154.750000
2015-02-04  120.510002  158.710007  NaN  221.479996  118.309998  156.699997
2015-02-05  120.230003  158.589996  NaN  225.479996  119.250000  157.149994
2015-02-06  120.250000  158.080002  NaN  223.399994  118.449997  156.229996
2015-02-09  119.839996  157.500000  NaN  217.929993  118.430000  155.399994
2015-02-10  122.150002  158.559998  NaN  220.500000  120.160004  155.080002
2015-02-11  124.919998  159.089996  NaN  214.740005  122.500000  157.169998
2015-02-12  127.480003  159.500000  NaN  203.089996  125.570000  158.089996
2015-02-13  127.279999  160.800003  NaN  205.990005  125.650002  158.639999
...                ...         ...  ...         ...         ...         ...
2019-02-22  173.000000  139.380005  NaN  296.500000  171.380005  138.429993
2019-02-25  175.869995  140.470001  NaN  302.899994  173.949997  139.320007
2019-02-26  175.300003  140.490005  NaN  302.010010  173.169998  139.470001
2019-02-27  175.000000  139.570007  NaN  316.299988  172.729996  138.399994
2019-02-28  174.910004  139.059998  NaN  320.000000  172.919998  137.720001
2019-03-01  175.149994  140.039993  NaN  307.130005  172.889999  138.639999
2019-03-04  177.750000  140.080002  NaN  299.000000  173.970001  137.169998
2019-03-05  176.000000  138.740005  NaN  284.000000  174.539993  137.559998
2019-03-06  175.490005  138.389999  NaN  281.510010  173.940002  136.720001
2019-03-07  174.440002  136.889999  NaN  284.700012  172.020004  134.630005
2019-03-08  173.070007  135.240005  NaN  285.589996  169.500000  133.580002
2019-03-11  179.119995  137.729996  NaN  291.279999  175.350006  135.839996
2019-03-12  182.669998  139.699997  NaN  288.070007  179.369995  137.860001
2019-03-13  183.300003  139.320007  NaN  291.989990  180.919998  137.850006
2019-03-14  184.100006  138.940002  NaN  295.390015  182.559998  138.059998
2019-03-15  187.330002  140.330002  NaN  283.720001  183.740005  139.229996
2019-03-18  188.389999  140.369995  NaN  278.049988  185.789993  138.720001
2019-03-19  188.990005  141.699997  NaN  273.299988  185.919998  140.000000
2019-03-20  189.490005  140.699997  NaN  274.970001  184.729996  138.979996
2019-03-21  196.330002  142.119995  NaN  276.450012  189.809998  138.880005
2019-03-22  197.690002  141.440002  NaN  272.799988  190.779999  138.899994
2019-03-25  191.979996  139.910004  NaN  263.179993  186.600006  138.350006
2019-03-26  192.880005  141.020004  NaN  270.260010  184.580002  139.419998
2019-03-27  189.759995  140.490005  NaN  275.369995  186.550003  138.399994
2019-03-28  189.559998  140.440002  NaN  280.329987  187.529999  139.100006
2019-03-29  190.080002  141.220001  NaN  280.160004  188.539993  140.149994
2019-04-01  191.679993  143.410004  NaN  289.200012  188.380005  141.509995
2019-04-02  194.460007  143.949997  NaN  289.440002  191.050003  142.600006
2019-04-03  196.500000  144.220001  NaN  296.170013  193.149994  143.009995
2019-04-04  196.360001  144.139999  NaN  271.200012  194.710007  142.539993

Attributes                         Open                 ...     Close  \
Symbols    LNKD        TSLA        AAPL         IBM     ...      LNKD
Date                                                    ...
2015-01-02  NaN  213.259995  111.389999  161.309998     ...       NaN
2015-01-05  NaN  207.160004  108.290001  161.270004     ...       NaN
2015-01-06  NaN  204.210007  106.540001  159.669998     ...       NaN
2015-01-07  NaN  209.779999  107.199997  157.199997     ...       NaN
2015-01-08  NaN  210.009995  109.230003  156.240005     ...       NaN
2015-01-09  NaN  204.960007  112.669998  158.419998     ...       NaN
2015-01-12  NaN  199.250000  112.599998  159.000000     ...       NaN
2015-01-13  NaN  200.910004  111.430000  157.259995     ...       NaN
2015-01-14  NaN  185.000000  109.040001  154.860001     ...       NaN
2015-01-15  NaN  190.000000  110.000000  156.690002     ...       NaN
2015-01-16  NaN  189.649994  107.029999  153.820007     ...       NaN
2015-01-20  NaN  187.039993  107.839996  156.699997     ...       NaN
2015-01-21  NaN  189.509995  108.949997  153.029999     ...       NaN
2015-01-22  NaN  195.199997  110.260002  151.940002     ...       NaN
2015-01-23  NaN  198.330002  112.300003  155.029999     ...       NaN
2015-01-26  NaN  201.050003  113.739998  158.259995     ...       NaN
2015-01-27  NaN  203.300003  112.419998  154.940002     ...       NaN
2015-01-28  NaN  198.419998  117.629997  154.000000     ...       NaN
2015-01-29  NaN  196.500000  116.320000  151.380005     ...       NaN
2015-01-30  NaN  203.000000  118.400002  153.910004     ...       NaN
2015-02-02  NaN  203.300003  118.050003  154.000000     ...       NaN
2015-02-03  NaN  211.270004  118.500000  154.750000     ...       NaN
2015-02-04  NaN  216.800003  118.500000  157.210007     ...       NaN
2015-02-05  NaN  219.639999  120.019997  157.289993     ...       NaN
2015-02-06  NaN  216.500000  120.019997  157.339996     ...       NaN
2015-02-09  NaN  211.990005  118.550003  156.000000     ...       NaN
2015-02-10  NaN  215.000000  120.169998  156.740005     ...       NaN
2015-02-11  NaN  207.279999  122.769997  157.759995     ...       NaN
2015-02-12  NaN  193.279999  126.059998  158.720001     ...       NaN
2015-02-13  NaN  200.910004  127.279999  158.779999     ...       NaN
...         ...         ...         ...         ...     ...       ...
2019-02-22  NaN  292.100006  171.580002  138.729996     ...       NaN
2019-02-25  NaN  297.000000  174.160004  140.000000     ...       NaN
2019-02-26  NaN  288.769989  173.710007  139.669998     ...       NaN
2019-02-27  NaN  300.549988  173.210007  139.250000     ...       NaN
2019-02-28  NaN  310.809998  174.320007  138.770004     ...       NaN
2019-03-01  NaN  291.899994  174.279999  139.309998     ...       NaN
2019-03-04  NaN  282.779999  175.690002  139.990005     ...       NaN
2019-03-05  NaN  270.100006  175.940002  138.369995     ...       NaN
2019-03-06  NaN  274.390015  174.669998  138.119995     ...       NaN
2019-03-07  NaN  274.250000  173.869995  136.610001     ...       NaN
2019-03-08  NaN  275.890015  170.320007  134.210007     ...       NaN
2019-03-11  NaN  280.500000  175.490005  136.029999     ...       NaN
2019-03-12  NaN  281.059998  180.000000  138.520004     ...       NaN
2019-03-13  NaN  282.700012  182.250000  138.050003     ...       NaN
2019-03-14  NaN  288.290009  183.899994  138.509995     ...       NaN
2019-03-15  NaN  274.399994  184.850006  139.369995     ...       NaN
2019-03-18  NaN  267.299988  185.800003  139.830002     ...       NaN
2019-03-19  NaN  263.459991  188.350006  140.960007     ...       NaN
2019-03-20  NaN  266.299988  186.229996  140.529999     ...       NaN
2019-03-21  NaN  268.450012  190.020004  139.100006     ...       NaN
2019-03-22  NaN  264.000000  195.339996  140.970001     ...       NaN
2019-03-25  NaN  254.460007  191.509995  139.059998     ...       NaN
2019-03-26  NaN  264.429993  191.660004  139.929993     ...       NaN
2019-03-27  NaN  268.179993  188.750000  140.410004     ...       NaN
2019-03-28  NaN  275.100006  188.949997  139.910004     ...       NaN
2019-03-29  NaN  274.500000  189.830002  140.500000     ...       NaN
2019-04-01  NaN  281.279999  191.639999  141.509995     ...       NaN
2019-04-02  NaN  283.880005  191.089996  143.350006     ...       NaN
2019-04-03  NaN  287.170013  193.250000  143.649994     ...       NaN
2019-04-04  NaN  260.589996  194.789993  143.619995     ...       NaN

Attributes                   Volume                                Adj Close  \
Symbols           TSLA         AAPL         IBM LNKD        TSLA        AAPL
Date
2015-01-02  219.309998   53204600.0   5525500.0  NaN   4764400.0  101.528191
2015-01-05  210.089996   64285500.0   4880400.0  NaN   5368500.0   98.667984
2015-01-06  211.279999   65797100.0   6146700.0  NaN   6261900.0   98.677261
2015-01-07  210.949997   40105900.0   4701800.0  NaN   2968400.0  100.060936
2015-01-08  210.619995   59364500.0   4236800.0  NaN   3442500.0  103.905510
2015-01-09  206.660004   53699500.0   4484800.0  NaN   4591300.0  104.016945
2015-01-12  202.210007   49650800.0   4182800.0  NaN   5944200.0  101.453903
2015-01-13  204.250000   67091900.0   4377500.0  NaN   4477300.0  102.354675
2015-01-14  192.690002   48337000.0   4690300.0  NaN  11551900.0  101.964645
2015-01-15  191.869995   60014000.0   4248400.0  NaN   5216500.0   99.197289
2015-01-16  193.070007   78513300.0   5756000.0  NaN   3603200.0   98.426529
2015-01-20  191.929993   49899900.0   8017800.0  NaN   4489400.0  100.961716
2015-01-21  196.570007   48575900.0  11897100.0  NaN   4153000.0  101.732506
2015-01-22  201.619995   53796400.0   6120100.0  NaN   4116900.0  104.379112
2015-01-23  201.289993   46464800.0   4812200.0  NaN   3438600.0  104.917725
2015-01-26  206.550003   55615000.0   7888100.0  NaN   3234500.0  105.029175
2015-01-27  205.979996   95568700.0   5659600.0  NaN   2781000.0  101.351738
2015-01-28  199.369995  146477100.0   4495900.0  NaN   3149600.0  107.081474
2015-01-29  205.199997   84436400.0   8320800.0  NaN   3548100.0  110.415276
2015-01-30  203.600006   83745500.0   6563600.0  NaN   3007000.0  108.799446
2015-02-02  210.940002   62739100.0   4712200.0  NaN   4149200.0  110.164543
2015-02-03  218.360001   51915700.0   5536300.0  NaN   4812900.0  110.183121
2015-02-04  218.550003   70149700.0   3678500.0  NaN   3305400.0  111.028168
2015-02-05  220.990005   42246200.0   5253600.0  NaN   3522900.0  111.820625
2015-02-06  217.360001   43706600.0   3225000.0  NaN   3233200.0  110.879021
2015-02-09  217.479996   38889800.0   3057700.0  NaN   3472400.0  111.615524
2015-02-10  216.289993   62008500.0   4440600.0  NaN   5390500.0  113.759834
2015-02-11  212.800003   73561800.0   3626700.0  NaN   9769100.0  116.426216
2015-02-12  202.880005   74474500.0   3333100.0  NaN  15649600.0  117.899254
2015-02-13  203.770004   54272200.0   3706900.0  NaN   6191000.0  118.477295
...                ...          ...         ...  ...         ...         ...
2019-02-22  294.709991   18913200.0   3113700.0  NaN   5740600.0  172.970001
2019-02-25  298.769989   21873400.0   3194200.0  NaN   6626500.0  174.229996
2019-02-26  297.859985   17070200.0   3060400.0  NaN   8582500.0  174.330002
2019-02-27  314.739990   27835400.0   2530900.0  NaN  11183900.0  174.869995
2019-02-28  319.880005   28215400.0   3457800.0  NaN  10520700.0  173.149994
2019-03-01  294.790009   25886200.0   3030000.0  NaN  22911400.0  174.970001
2019-03-04  285.359985   27436200.0   3406900.0  NaN  17096800.0  175.850006
2019-03-05  276.540009   19737400.0   4250300.0  NaN  18764700.0  175.529999
2019-03-06  276.239990   20810400.0   2768300.0  NaN  10335500.0  174.520004
2019-03-07  276.589996   24796400.0   4358800.0  NaN   9442500.0  172.500000
2019-03-08  284.140015   23999400.0   3773600.0  NaN   8819600.0  172.910004
2019-03-11  290.920013   32011000.0   3939300.0  NaN   7392300.0  178.899994
2019-03-12  283.359985   32467600.0   3954700.0  NaN   7504100.0  180.910004
2019-03-13  288.959991   31032500.0   3173200.0  NaN   6844700.0  181.710007
2019-03-14  289.959991   23579500.0   2738600.0  NaN   7103400.0  183.729996
2019-03-15  275.429993   39042900.0   7153700.0  NaN  14785500.0  186.119995
2019-03-18  269.489990   26219800.0   3268500.0  NaN  10281000.0  188.020004
2019-03-19  267.470001   31646400.0   3482300.0  NaN  11800600.0  186.529999
2019-03-20  273.600006   31035200.0   3649500.0  NaN   6908200.0  188.160004
2019-03-21  274.019989   51034200.0   3605400.0  NaN   5947100.0  195.089996
2019-03-22  264.529999   42407700.0   3877200.0  NaN   8745600.0  191.050003
2019-03-25  260.420013   43845300.0   2839800.0  NaN  10215000.0  188.740005
2019-03-26  267.769989   49800500.0   2553700.0  NaN   7350900.0  186.789993
2019-03-27  274.829987   29848400.0   3098200.0  NaN   8779200.0  188.470001
2019-03-28  278.619995   20780400.0   2663900.0  NaN   6774100.0  188.720001
2019-03-29  279.859985   23564000.0   3101400.0  NaN   5991300.0  189.949997
2019-04-01  289.179993   27862000.0   3984300.0  NaN   8110400.0  191.240005
2019-04-02  285.880005   22765700.0   2404800.0  NaN   5478900.0  194.020004
2019-04-03  291.809998   23249700.0   2681200.0  NaN   7919400.0  195.350006
2019-04-04  267.779999   18747318.0   2706066.0  NaN  23534862.0  195.690002

Attributes
Symbols            IBM LNKD        TSLA
Date
2015-01-02  135.278397  NaN  219.309998
2015-01-05  133.149841  NaN  210.089996
2015-01-06  130.278320  NaN  211.279999
2015-01-07  129.426880  NaN  210.949997
2015-01-08  132.239990  NaN  210.619995
2015-01-09  132.815948  NaN  206.660004
2015-01-12  130.587219  NaN  202.210007
2015-01-13  130.896027  NaN  204.250000
2015-01-14  130.052948  NaN  192.690002
2015-01-15  129.026199  NaN  191.869995
2015-01-16  131.171494  NaN  193.070007
2015-01-20  131.012863  NaN  191.929993
2015-01-21  126.956032  NaN  196.570007
2015-01-22  129.710678  NaN  201.619995
2015-01-23  130.111374  NaN  201.289993
2015-01-26  130.520401  NaN  206.550003
2015-01-27  128.274918  NaN  205.979996
2015-01-28  126.505280  NaN  199.369995
2015-01-29  129.785812  NaN  205.199997
2015-01-30  127.974457  NaN  203.600006
2015-02-02  129.101334  NaN  210.940002
2015-02-03  132.281693  NaN  218.360001
2015-02-04  131.021240  NaN  218.550003
2015-02-05  131.814255  NaN  220.990005
2015-02-06  131.738586  NaN  217.360001
2015-02-09  130.923187  NaN  217.479996
2015-02-10  133.285309  NaN  216.289993
2015-02-11  132.982666  NaN  212.800003
2015-02-12  133.251663  NaN  202.880005
2015-02-13  134.831985  NaN  203.770004
...                ...  ...         ...
2019-02-22  139.250000  NaN  294.709991
2019-02-25  139.460007  NaN  298.769989
2019-02-26  139.720001  NaN  297.859985
2019-02-27  139.169998  NaN  314.739990
2019-02-28  138.130005  NaN  319.880005
2019-03-01  139.199997  NaN  294.790009
2019-03-04  138.429993  NaN  285.359985
2019-03-05  137.880005  NaN  276.540009
2019-03-06  136.979996  NaN  276.239990
2019-03-07  135.360001  NaN  276.589996
2019-03-08  135.089996  NaN  284.140015
2019-03-11  137.710007  NaN  290.920013
2019-03-12  138.279999  NaN  283.359985
2019-03-13  138.559998  NaN  288.959991
2019-03-14  138.789993  NaN  289.959991
2019-03-15  139.429993  NaN  275.429993
2019-03-18  140.210007  NaN  269.489990
2019-03-19  140.490005  NaN  267.470001
2019-03-20  139.600006  NaN  273.600006
2019-03-21  141.440002  NaN  274.019989
2019-03-22  139.449997  NaN  264.529999
2019-03-25  139.179993  NaN  260.420013
2019-03-26  140.220001  NaN  267.769989
2019-03-27  139.240005  NaN  274.829987
2019-03-28  139.919998  NaN  278.619995
2019-03-29  141.100006  NaN  279.859985
2019-04-01  143.300003  NaN  289.179993
2019-04-02  143.000000  NaN  285.880005
2019-04-03  143.630005  NaN  291.809998
2019-04-04  142.779999  NaN  267.779999

[1071 rows x 24 columns]>

### Step 7. Good, now we know  the data avaiable. Create a dataFrame called vol, with the Volume values.

### Step 8. Aggregate the data of Volume to weekly
#### Hint: Be careful to not sum data from the same week of 2015 and other years.

### Step 9. Find all the volume traded in the year of 2015

### BONUS: Create your own question and answer it.